#include <stdio.h>



/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/


int main() {


    int evenValuedSum=0,twoBack=0,oneBack=1;

    for (int i = 1; i <= 4000000; i) {
        i=twoBack+oneBack;
        twoBack=oneBack;
        oneBack=i;

        if(i%2==0){
            evenValuedSum+=i;

        }
    }
    printf("Sum of even valued Fibonacci numbers: %d",evenValuedSum);

    return 0;
}